#!/usr/bin/python3

"""
This script is used to infer images.
"""

import argparse
from det_img_seg.seg_inference import SegInference

def main():
    pass



def infer():
    """
    Run inference on the given image
    """
    model = "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
    weights = "/home/jiasen/data/model/mask_rcnn_R_50_FPN_3x"
    image_dir = "/home/jiasen/data/dataset/merged/images"
    thing_classes = ["cheez_it"]
    inferencer = SegInference(model, weights, image_dir, thing_classes)
    inferencer.infer_dir()


if __name__ == "__main__":
    infer()
