#!/usr/bin/python3

"""
Train a model on the given dataset.
"""

import argparse
from det_img_seg.seg_train import SegTrainer

def main():
    parser = argparse.ArgumentParser(description="Train a model on the given dataset.")
    parser.add_argument("--model", type=str, required=True, help="Model to use")
    parser.add_argument("--weights", type=str, required=True, help="Weights to use")
    parser.add_argument("--dataset_dir", type=str, required=True, help="Dataset directory")
    parser.add_argument("--output_dir", type=str, required=True, help="Output directory")
    args = parser.parse_args()
    # initialize the trainer
    thing_classes = ["cheez_it"]
    trainer = SegTrainer(args.model, args.weights, args.dataset_dir, args.output_dir, thing_classes)
    # initialize the config
    trainer.init_cfg()
    # train the model
    trainer.train()

if __name__ == "__main__":
    main()
