#!/usr/bin/python3

"""
Train a model on the given dataset.
"""

import argparse
from det_img_seg.seg_train import SegTrainer

def main():
    parser = argparse.ArgumentParser(description="Train a model on the given dataset.")
    parser.add_argument("--model", type=str, required=True, help="Model to use")
    parser.add_argument("--weights", type=str, required=True, help="Weights to use")
    parser.add_argument("--dataset_dir", type=str, required=True, help="Dataset directory")
    parser.add_argument("--output_dir", type=str, required=True, help="Output directory")
    args = parser.parse_args()
    # initialize the trainer
    thing_classes = ["cheez_it"]
    trainer = SegTrainer(args.model, args.weights, args.dataset_dir, args.output_dir, thing_classes)
    # initialize the config
    trainer.init_cfg()
    # train the model
    trainer.train()

def train():
    """
    Train the model
    """
    model = "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
    weights = "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
    dataset_dir = "/home/jiasen/data/dataset/merged"
    output_dir = "/home/jiasen/data/model/mask_rcnn_R_50_FPN_3x"
    thing_classes = ["cheez_it"]
    trainer = SegTrainer(model, weights, dataset_dir, output_dir, thing_classes)
    trainer.init_cfg()
    trainer.train()

if __name__ == "__main__":
    train()
